-- main : Html msg
-- main =
--     -- Remember: all Html elements available are functions
--     -- Each takes 2 arguments: attributs and children
--     div [ class "a-class-name" ] [ text "Hello world" ]
